services:
  xiaoya-search-tool:
    build: .
    container_name: xiaoya-search-tool
    restart: unless-stopped
    ports:
      - "5666:5666"
    volumes:
      # 挂载宿主机的 index.txt 文件到容器内，默认为 /etc/xiaoya/index.txt
      # 请根据实际情况修改宿主机路径，例如：/path/to/your/xiaoya/index.txt:/etc/xiaoya/index.txt
      - /data/app/g-box/index/index.txt:/etc/xiaoya/index.txt:ro
      - ./downloads:/downloads
    env_file:
      - .env
    environment:
      # 可以在这里覆盖环境变量，或者直接使用 .env 文件
      - PYTHONUNBUFFERED=1
